import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { TanstackProvider } from "@/providers/tanstack-provider";
import ResumeInfoProvider from "@/contexts/resume-info";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackProvider>
          <Header />
          <ResumeInfoProvider>
            <Toaster position="top-right" />
            {children}
          </ResumeInfoProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
